### ISSUE TITLE
Concurrent modification on stop game

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#103]
When I stopped the game one time, immediately after a player who was not on any teams joined the server, I got a `ConcurrentModificationException` that looked like the following:
```
[14:38:57 INFO]: Braekpo1nt issued server command: /mct game stop
[14:38:57 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mct' in plugin MCTManager v0.2.0-alpha
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-384]
at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-384]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-384]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
at org.braekpo1nt.mctmanager.games.footrace.FootRaceGame.stop(FootRaceGame.java:108) ~[MCTManager-0.2.0-alpha-all.jar:?]
at org.braekpo1nt.mctmanager.games.GameManager.manuallyStopGame(GameManager.java:225) ~[MCTManager-0.2.0-alpha-all.jar:?]
at org.braekpo1nt.mctmanager.commands.game.StopSubCommand.onCommand(StopSubCommand.java:32) ~[MCTManager-0.2.0-alpha-all.jar:?]
at org.braekpo1nt.mctmanager.commands.game.GameSubCommand.onCommand(GameSubCommand.java:37) ~[MCTManager-0.2.0-alpha-all.jar:?]
at org.braekpo1nt.mctmanager.commands.MCTCommand.onCommand(MCTCommand.java:70) ~[MCTManager-0.2.0-alpha-all.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
... 23 more
```

**Comment by Braekpo1nt** [comment]
this is likely caused by iterating over the objects while I was deleting them, as in #60
