### ISSUE TITLE
BossBar display for colossal combat

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#518]
## Description
Make it exactly like the one for capture the flag

## Definition of Done
- [x] handles player/spectator leaving
  - [x] during description
  - [x] during round starting countdown
  - [x] during round
- [x] handles player/spectator joining
  - [x] during description
  - [x] during round starting countdown
  - [x] during round
- [x] errors in comments below are fixed

## Related Issues
- #503

**Comment by Braekpo1nt** [comment]
```
[08:43:33 INFO]: Kbelleflash was slain by Braekpo1nt
[08:43:33 ERROR]: Could not pass event PlayerDeathEvent to MCTManager v1.0.0
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
at org.braekpo1nt.mctmanager.games.colossalcombat.ColossalCombatGame.addKill(ColossalCombatGame.java:540) ~[MCTManager-1.0.0-all.jar:?]
at org.braekpo1nt.mctmanager.games.colossalcombat.ColossalCombatRound.onParticipantGetKill(ColossalCombatRound.java:373) ~[MCTManager-1.0.0-all.jar:?]
at org.braekpo1nt.mctmanager.games.colossalcombat.ColossalCombatRound.onPlayerDeath(ColossalCombatRound.java:335) ~[MCTManager-1.0.0-all.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1468.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-384]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:907) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:908) ~[?:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1491) ~[?:?]
at net.minecraft.world.entity.player.Player.hurt(Player.java:961) ~[?:?]
at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1071) ~[?:?]
at net.minecraft.world.entity.player.Player.attack(Player.java:1314) ~[?:?]
at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2118) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2836) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2760) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-384]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Braekpo1nt** [comment]
Error:
- capture the flag
- 2 players on yellow, one leaves during description phase
- that player logs back on, and their left bossbar section says "On Deck"
