### ISSUE TITLE
MECHA handle players leaving and joining

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#60]
Foot Race already handles players leaving and rejoining as of #104 . 

Re-vamp mecha to do the same. Model it after foot race.

**Comment by Braekpo1nt** [comment]
Related to #104 
A lot of this code was figured out in that issue. Foot race can now do this, I should implement this in MECHA

**Comment by Braekpo1nt** [comment]
Getting the following error: 
```
[16:46:16 INFO]: Braekpo1nt issued server command: /mct game start mecha
[16:46:16 INFO]: Started mecha
[16:46:37 INFO]: Braekpo1nt issued server command: /kick rstln
[16:46:37 INFO]: rstln lost connection: Kicked by an operator
[16:46:37 INFO]: rstln left early. Their life is forfeit.
[16:46:37 INFO]: Team Green wins!
[16:46:37 INFO]: rstln left the game
[16:46:37 INFO]: [Braekpo1nt: Kicked rstln: Kicked by an operator]
[16:46:47 WARN]: [MCTManager] Task #1415 for MCTManager v0.2.0-alpha generated an exception
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
at org.braekpo1nt.mctmanager.games.mecha.MechaGame.stop(MechaGame.java:126) ~[MCTManager-0.2.0-alpha-all.jar:?]
at org.braekpo1nt.mctmanager.games.mecha.MechaGame$2.run(MechaGame.java:227) ~[MCTManager-0.2.0-alpha-all.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-384]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-384]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Braekpo1nt** [comment]
Resolved ConcurrentModificationException. I was iterating through the participants as I was removing them.
