### ISSUE TITLE
Round Manager doesn't utilize all maps

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#608]
## Describe the bug
When there are 10 teams and 5 arenas, only 4 are used, resulting in long stretches of the same teams being on deck multiple times in a row.

## To Reproduce
- Play CTF with 10 teams and 5 arenas

## Expected behavior
There should be 9 rounds, not 15, and no teams should be on-deck through the entire game.

## Definition of Done
- [x] expected behavior above 
- [x] I noticed some funkiness with when the timer gets cancelled. the countdown for the final match conflicts with the game over countdown 
```
[22:51:10 INFO]: [MCTManager] Starting Capture the Flag
[22:51:15 INFO]: Kbelleflash lost connection: Disconnected
[22:51:15 INFO]: Kbelleflash left the game
mct timer skip
mct timer skip
[22:51:21 INFO]: [MCTManager] Starting capture the flag match {purple vs red}
mct timer skip
[22:51:23 INFO]: Begin!
[22:51:23 INFO]: Red Rangers is absent, match cancelled.
[22:51:23 INFO]: [MCTManager] Stopping capture the flag match {purple vs red}
[22:51:23 INFO]: [MCTManager] hasNextRound============
[22:51:48 INFO]: [MCTManager] Starting capture the flag match {pink vs red}
[22:52:08 INFO]: Begin!
[22:52:08 INFO]: Red Rangers is absent, match cancelled.
[22:52:08 INFO]: [MCTManager] Stopping capture the flag match {pink vs red}
[22:52:08 INFO]: [MCTManager] hasNextRound============
[22:52:33 INFO]: [MCTManager] Starting capture the flag match {pink vs purple}
[22:52:53 INFO]: Begin!
[22:54:20 INFO]: UUID of player Kbelleflash is baa80b76-1f45-4f86-b984-3861d5e2d97e
[22:54:22 INFO]: Kbelleflash joined the game
[22:54:22 INFO]: Kbelleflash[/72.94.39.92:52278] logged in with entity id 10246 at ([FT]106.0, 0.0, -1000.0)
[22:54:46 INFO]: Purple Paladins captured Pink Penguins's flag!
[22:54:46 INFO]: [MCTManager] Stopping capture the flag match {pink vs purple}
[22:54:46 WARN]: rstln moved too quickly! -15.0,16.0,43.0
[22:54:46 WARN]: Braekpo1nt moved too quickly! -24.135499008021384,16.0,5.905131458794699
[22:54:56 INFO]: [MCTManager] Stopping Capture the Flag
```

**Comment by Braekpo1nt** [comment]
- Start with 3 teams
- After rounds are announced to the players with titles, one of the teams who is in the first match quits
- After the first round's class selection timer is up, the match is ended (which ends the round)
- At this point, the timer should update to show how many seconds are left in the RoundOverState, but instead the 3-minute timer for RoundActiveState is still up.

**Comment by Braekpo1nt** [comment]
Errors occur when players quit at a certain point:
```
[14:51:34 INFO]: [MCTManager] Starting Capture the Flag
[14:51:34 WARN]: Braekpo1nt moved too quickly! -6.190905862287849,-1.0,-8.343983804704635
mct timer skip
mct timer skip
[14:51:40 INFO]: [MCTManager] Starting capture the flag match {purple vs red}
[14:51:40 WARN]: Braekpo1nt moved too quickly! 14.196891070986709,-16.0,-46.608057632525174
[14:51:40 WARN]: Kbelleflash moved too quickly! 15.0,-16.0,-3.0
mct timer skip
[14:51:42 INFO]: Begin!
[14:51:58 INFO]: Purple Paladins captured Red Rangers's flag!
[14:51:58 INFO]: [MCTManager] MatchOverState instantiated
[14:51:58 INFO]: [MCTManager] 1/1 matches are complete, ending round
[14:51:58 INFO]: [MCTManager] roundTimer is cancelled
[14:51:58 INFO]: [MCTManager] Stopping capture the flag match {purple vs red}
[14:51:58 INFO]: [MCTManager] Starting RoundOverState timer
[14:51:58 WARN]: Kbelleflash moved too quickly! -15.0,16.0,3.0
[14:51:58 WARN]: Braekpo1nt moved too quickly! -6.6972693870504685,16.0,39.30747846204963
mct timer pause
[14:57:18 INFO]: Braekpo1nt lost connection: Disconnected
[14:57:18 INFO]: [MCTManager] Round 0:
[14:57:18 INFO]: [MCTManager] - {green vs red}
[14:57:18 INFO]: Braekpo1nt left the game
[14:57:20 INFO]: rstln lost connection: Disconnected
[14:57:20 ERROR]: Could not pass event PlayerQuitEvent to MCTManager v1.2.0
java.lang.IllegalArgumentException: There must be at least two teamIds (got 1)
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[guava-32.1.2-jre.jar:?]
at MCTManager-1.2.0.jar/org.braekpo1nt.mctmanager.games.game.capturetheflag.RoundManager.regenerateRounds(RoundManager.java:109) ~[MCTManager-1.2.0.jar:?]
at MCTManager-1.2.0.jar/org.braekpo1nt.mctmanager.games.game.capturetheflag.states.RoundOverState.onParticipantQuit(RoundOverState.java:60) ~[MCTManager-1.2.0.jar:?]
at MCTManager-1.2.0.jar/org.braekpo1nt.mctmanager.games.game.capturetheflag.CaptureTheFlagGame.onParticipantQuit(CaptureTheFlagGame.java:205) ~[MCTManager-1.2.0.jar:?]
at MCTManager-1.2.0.jar/org.braekpo1nt.mctmanager.games.GameManager.onParticipantQuit(GameManager.java:330) ~[MCTManager-1.2.0.jar:?]
at MCTManager-1.2.0.jar/org.braekpo1nt.mctmanager.games.GameManager.playerQuitEvent(GameManager.java:299) ~[MCTManager-1.2.0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1126.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-109-5a5035b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-109-5a5035b]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-109-5a5035b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.players.PlayerList.remove(PlayerList.java:605) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.players.PlayerList.remove(PlayerList.java:590) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2036) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2016) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2003) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.network.Connection.handleDisconnection(Connection.java:902) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:262) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1822) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1597) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-109-5a5035b]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:57:20 INFO]: rstln left the game
[14:57:22 INFO]: Kbelleflash lost connection: Disconnected
[14:57:22 ERROR]: Could not pass event PlayerQuitEvent to MCTManager v1.2.0
java.lang.IllegalArgumentException: There must be at least two teamIds (got 0)
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[guava-32.1.2-jre.jar:?]
at MCTManager-1.2.0.jar/org.braekpo1nt.mctmanager.games.game.capturetheflag.RoundManager.regenerateRounds(RoundManager.java:109) ~[MCTManager-1.2.0.jar:?]
at MCTManager-1.2.0.jar/org.braekpo1nt.mctmanager.games.game.capturetheflag.states.RoundOverState.onParticipantQuit(RoundOverState.java:60) ~[MCTManager-1.2.0.jar:?]
at MCTManager-1.2.0.jar/org.braekpo1nt.mctmanager.games.game.capturetheflag.CaptureTheFlagGame.onParticipantQuit(CaptureTheFlagGame.java:205) ~[MCTManager-1.2.0.jar:?]
at MCTManager-1.2.0.jar/org.braekpo1nt.mctmanager.games.GameManager.onParticipantQuit(GameManager.java:330) ~[MCTManager-1.2.0.jar:?]
at MCTManager-1.2.0.jar/org.braekpo1nt.mctmanager.games.GameManager.playerQuitEvent(GameManager.java:299) ~[MCTManager-1.2.0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1126.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-109-5a5035b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-109-5a5035b]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-109-5a5035b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.players.PlayerList.remove(PlayerList.java:605) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.players.PlayerList.remove(PlayerList.java:590) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2036) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2016) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2003) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.network.Connection.handleDisconnection(Connection.java:902) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:262) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1822) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1597) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303) ~[paper-1.21.jar:1.21-109-5a5035b]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-109-5a5035b]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:57:22 INFO]: Kbelleflash left the game
mct game stop false
[14:57:34 INFO]: Skipping teleport to hub.
[14:57:34 INFO]: [MCTManager] Stopping Capture the Flag

```
